<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SoftTalkIme.Cli</RootNamespace>
    <AssemblyName>SoftTalkIme.Cli</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SoftTalkIme.Core\SoftTalkIme.Core.csproj" />
  </ItemGroup>
</Project>
